# Generated by Django 5.0 on 2024-01-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=20)),
                ('user_log_state', models.BooleanField(default=False)),
            ],
        ),
    ]
